refinery: refinery/refinerycms
radiant: radiant/radiant
zena: zena/zena
adva: svenfuchs/adva_cms
djangocms: divio/django-cms
nesta: gma/nesta
browsercms: browsermedia/browsercms
pyro: pyrocms/pyrocms
locomotivecms: locomotivecms/engine
